development:
  host: localhost
  database: bllbrd_development

# test:
#   host: localhost
#   database: bllbrd_test

# set these environment variables on your prod server
production:
  host: localhost
  database: bllbrd_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
